# Generated by Django 2.2.5 on 2020-05-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_instalaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('default', 'Captador'), ('coordinador', 'Coordinador')], default='default', max_length=30, verbose_name='Rol'),
        ),
    ]
