# Generated by Django 2.2.5 on 2020-05-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('default', 'Captador'), ('coordinador', 'Coordinador')], max_length=30, null=True, verbose_name='Rol'),
        ),
    ]
