# Generated by Django 2.2.5 on 2019-09-15 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('political_division', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=150)),
                ('cod_reg', models.CharField(max_length=2)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='political_division.Provincia')),
            ],
        ),
    ]
