# Generated by Django 2.2.5 on 2019-09-15 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('political_division', '0003_distrito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corregimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corregimiento', models.CharField(max_length=150)),
                ('cod_corr', models.CharField(max_length=2)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='political_division.Distrito')),
            ],
        ),
    ]
