# Generated by Django 2.2.5 on 2019-09-15 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('political_division', '0004_corregimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poblado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poblado', models.CharField(max_length=150)),
                ('cod_pob', models.CharField(max_length=2)),
                ('corregimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='political_division.Corregimiento')),
            ],
        ),
    ]
