# Generated by Django 2.2.5 on 2019-09-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('political_division', '0007_auto_20190925_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='corregimiento',
            name='poligono_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='distrito',
            name='poligono_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='provincia',
            name='poligono_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='corregimiento',
            name='cod_corr',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='cod_dist',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='poblado',
            name='cod_pob',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='cod_reg',
            field=models.CharField(max_length=4),
        ),
    ]
