# Generated by Django 2.2.5 on 2019-09-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('political_division', '0008_auto_20190925_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corregimiento',
            name='cod_corr',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='cod_dist',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='cod_prov',
            field=models.CharField(blank=True, max_length=2, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='cod_reg',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
