# Generated by Django 2.2.5 on 2019-10-22 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('political_division', '0010_auto_20190925_1928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corregimiento',
            options={'verbose_name': 'Corregimiento', 'verbose_name_plural': 'Corregimientos'},
        ),
        migrations.AlterModelOptions(
            name='distrito',
            options={'verbose_name': 'Distrito', 'verbose_name_plural': 'Distritos'},
        ),
        migrations.AlterModelOptions(
            name='poblado',
            options={'verbose_name': 'Poblado', 'verbose_name_plural': 'Poblados'},
        ),
        migrations.AlterModelOptions(
            name='provincia',
            options={'verbose_name': 'Provincia', 'verbose_name_plural': 'Provincias'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Región', 'verbose_name_plural': 'Regiones'},
        ),
        migrations.AlterField(
            model_name='corregimiento',
            name='cod_corr',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='corregimiento',
            name='corregimiento',
            field=models.CharField(max_length=150, verbose_name='Corregimiento'),
        ),
        migrations.AlterField(
            model_name='corregimiento',
            name='distrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='political_division.Distrito', verbose_name='Distrito'),
        ),
        migrations.AlterField(
            model_name='corregimiento',
            name='poligono_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Polígono Id'),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='cod_dist',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='distrito',
            field=models.CharField(max_length=150, verbose_name='Distrito'),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='poligono_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Polígono Id'),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='provincia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='political_division.Provincia', verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='political_division.Region', verbose_name='Región'),
        ),
        migrations.AlterField(
            model_name='poblado',
            name='cod_pob',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='poblado',
            name='corregimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='political_division.Corregimiento', verbose_name='Corregimiento'),
        ),
        migrations.AlterField(
            model_name='poblado',
            name='poblado',
            field=models.CharField(max_length=150, verbose_name='Poblado'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='cod_prov',
            field=models.CharField(blank=True, max_length=2, null=True, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='poligono_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Polígono Id'),
        ),
        migrations.AlterField(
            model_name='region',
            name='cod_reg',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='region',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='political_division.Provincia', verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region',
            field=models.CharField(max_length=150, verbose_name='Región'),
        ),
    ]
