# Generated by Django 2.2.5 on 2019-10-24 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('political_division', '0011_auto_20191022_1418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corregimiento',
            options={'verbose_name': 'corregimiento', 'verbose_name_plural': 'corregimientos'},
        ),
        migrations.AlterModelOptions(
            name='distrito',
            options={'verbose_name': 'distrito', 'verbose_name_plural': 'distritos'},
        ),
        migrations.AlterModelOptions(
            name='poblado',
            options={'verbose_name': 'poblado', 'verbose_name_plural': 'poblados'},
        ),
        migrations.AlterModelOptions(
            name='provincia',
            options={'verbose_name': 'provincia', 'verbose_name_plural': 'provincias'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'región de salud', 'verbose_name_plural': 'regiones de salud'},
        ),
    ]
