# Generated by Django 2.2.5 on 2019-10-25 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('political_division', '0012_auto_20191024_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corregimiento',
            options={'ordering': ['corregimiento'], 'verbose_name': 'corregimiento', 'verbose_name_plural': 'corregimientos'},
        ),
        migrations.AlterModelOptions(
            name='distrito',
            options={'ordering': ['distrito'], 'verbose_name': 'distrito', 'verbose_name_plural': 'distritos'},
        ),
        migrations.AlterModelOptions(
            name='poblado',
            options={'ordering': ['poblado'], 'verbose_name': 'poblado', 'verbose_name_plural': 'poblados'},
        ),
        migrations.AlterModelOptions(
            name='provincia',
            options={'ordering': ['provincia'], 'verbose_name': 'provincia', 'verbose_name_plural': 'provincias'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['region'], 'verbose_name': 'región de salud', 'verbose_name_plural': 'regiones de salud'},
        ),
    ]
