# Generated by Django 2.2.5 on 2019-10-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('political_division', '0013_auto_20191025_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='poblado',
            name='contra_key',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Llave de contraloria'),
        ),
    ]
