# Generated by Django 2.2.5 on 2019-10-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('political_division', '0014_poblado_contra_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poblado',
            name='contra_key',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Llave de contraloria'),
        ),
    ]
