# Generated by Django 2.2.5 on 2019-09-15 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('political_division', '0006_auto_20190915_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependencia', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoInstalacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_instalacion', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instalacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instalacion', models.CharField(max_length=150)),
                ('corregimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='political_division.Corregimiento')),
                ('dependencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='facilities.Dependencia')),
                ('nivel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='facilities.Nivel')),
                ('tipo_instalacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='facilities.TipoInstalacion')),
            ],
        ),
    ]
