# Generated by Django 2.2.5 on 2019-09-15 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('political_division', '0006_auto_20190915_1402'),
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstalacionPoblado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instalacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.Instalacion')),
                ('poblado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='political_division.Poblado')),
            ],
        ),
    ]
