# Generated by Django 2.2.5 on 2019-09-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_instalacionpoblado'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='instalacionpoblado',
            constraint=models.UniqueConstraint(fields=('instalacion', 'poblado'), name='unique_instalacion_poblado'),
        ),
    ]
