# Generated by Django 2.2.5 on 2019-09-26 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('political_division', '0010_auto_20190925_1928'),
        ('facilities', '0005_auto_20190926_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacion',
            name='region_dependencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='political_division.Region'),
        ),
    ]
