# Generated by Django 2.2.5 on 2019-09-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0006_instalacion_region_dependencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalacion',
            name='cod_inst',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
