# Generated by Django 2.2.5 on 2019-10-22 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0008_auto_20190926_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=150, verbose_name='Servicio')),
                ('codigo', models.CharField(max_length=2, unique=True, verbose_name='Código')),
            ],
        ),
        migrations.AlterModelOptions(
            name='dependencia',
            options={'verbose_name': 'Dependencia', 'verbose_name_plural': 'Dependencias'},
        ),
        migrations.AlterModelOptions(
            name='instalacion',
            options={'verbose_name': 'Instalación', 'verbose_name_plural': 'Instalaciones'},
        ),
        migrations.AlterModelOptions(
            name='nivel',
            options={'verbose_name': 'Nivel', 'verbose_name_plural': 'Niveles'},
        ),
        migrations.AlterModelOptions(
            name='tipoinstalacion',
            options={'verbose_name': 'Tipo de instalación', 'verbose_name_plural': 'Tipo de instalaciones'},
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='codigo',
            field=models.CharField(max_length=2, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='dependencia',
            field=models.CharField(max_length=150, verbose_name='Dependencia'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='cod_inst',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='corregimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='political_division.Corregimiento', verbose_name='Corregimiento'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='dependencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='facilities.Dependencia', verbose_name='Dependencia'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='instalacion',
            field=models.CharField(max_length=150, verbose_name='Instalación'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='nivel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='facilities.Nivel', verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='region_dependencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='political_division.Region', verbose_name='Región Asociada'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='tipo_instalacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='facilities.TipoInstalacion', verbose_name='Tipo de Instalación'),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='codigo',
            field=models.CharField(max_length=2, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='nivel',
            field=models.CharField(max_length=150, verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='tipoinstalacion',
            name='codigo',
            field=models.CharField(max_length=2, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='tipoinstalacion',
            name='tipo_instalacion',
            field=models.CharField(max_length=150, verbose_name='Tipo de Instalación'),
        ),
        migrations.AddField(
            model_name='instalacion',
            name='servicios',
            field=models.ManyToManyField(to='facilities.Servicio'),
        ),
    ]
