# Generated by Django 2.2.5 on 2019-10-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0009_auto_20191022_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalacion',
            name='servicios',
            field=models.ManyToManyField(blank=True, null=True, to='facilities.Servicio'),
        ),
    ]
