# Generated by Django 2.2.5 on 2019-10-22 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0011_auto_20191022_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(max_length=150, verbose_name='Horario')),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('instalacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.Instalacion', verbose_name='Instalación')),
            ],
        ),
    ]
