# Generated by Django 2.2.5 on 2019-10-23 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0012_horario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ('servicio',)},
        ),
        migrations.AlterField(
            model_name='horario',
            name='closing_time',
            field=models.TimeField(verbose_name='Fin'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='opening_time',
            field=models.TimeField(verbose_name='Inicio'),
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=150, verbose_name='Número')),
                ('phone_choise', models.IntegerField(choices=[(1, 'Teléfono'), (2, 'Celular'), (3, 'Fax')], default=1)),
                ('instalacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.Instalacion', verbose_name='Instalación')),
            ],
        ),
    ]
