# Generated by Django 2.2.5 on 2019-10-23 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0013_auto_20191023_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=150, verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Cargos',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name': 'Contactos', 'verbose_name_plural': 'Contactos'},
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_choise',
            field=models.IntegerField(choices=[(1, 'Teléfono'), (2, 'Celular'), (3, 'Fax')], default=1, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_minsa', models.CharField(max_length=5, unique=True, verbose_name='Identificador Institucional')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('identity_card', models.CharField(max_length=13, verbose_name='Cédula')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Salario Mensual')),
                ('start_date', models.TimeField(verbose_name='Inicio de labores')),
                ('status', models.IntegerField(choices=[(1, 'PERMANENTE'), (2, 'PERS TRANS DE INVERS'), (3, 'PERS TRANSITORIO')], default=1, verbose_name='Estatus')),
                ('job_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='facilities.Position', verbose_name='Cargo')),
            ],
        ),
    ]
