# Generated by Django 2.2.5 on 2019-10-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0014_auto_20191023_2134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Funcionarios', 'verbose_name_plural': 'Funcionarios'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='start_date',
            field=models.DateField(verbose_name='Inicio de labores'),
        ),
    ]
