# Generated by Django 2.2.5 on 2019-10-24 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0015_auto_20191023_2138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dependencia',
            options={'verbose_name': 'dependencia', 'verbose_name_plural': 'dependencias'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'funcionario', 'verbose_name_plural': 'funcionarios'},
        ),
        migrations.AlterModelOptions(
            name='instalacion',
            options={'verbose_name': 'instalación', 'verbose_name_plural': 'instalaciones'},
        ),
        migrations.AlterModelOptions(
            name='nivel',
            options={'verbose_name': 'nivel', 'verbose_name_plural': 'niveles'},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name': 'contacto', 'verbose_name_plural': 'contactos'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'cargo', 'verbose_name_plural': 'cargos'},
        ),
        migrations.AlterModelOptions(
            name='tipoinstalacion',
            options={'verbose_name': 'tipo de instalación', 'verbose_name_plural': 'tipos de instalación'},
        ),
        migrations.AddField(
            model_name='employee',
            name='instalacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facilities.Instalacion', verbose_name='Instalacion'),
        ),
        migrations.AddField(
            model_name='employee',
            name='spend_object',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Objeto de gasto'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facilities.Position', verbose_name='Cargo'),
        ),
    ]
