# Generated by Django 2.2.5 on 2019-10-24 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0016_auto_20191024_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['name', 'last_name'], 'verbose_name': 'funcionario', 'verbose_name_plural': 'funcionarios'},
        ),
        migrations.AlterModelOptions(
            name='instalacion',
            options={'ordering': ['instalacion'], 'verbose_name': 'instalación', 'verbose_name_plural': 'instalaciones'},
        ),
        migrations.AlterModelOptions(
            name='tipoinstalacion',
            options={'ordering': ['tipo_instalacion'], 'verbose_name': 'tipo de instalación', 'verbose_name_plural': 'tipos de instalación'},
        ),
    ]
