# Generated by Django 2.2.5 on 2019-10-25 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0017_auto_20191024_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['position'], 'verbose_name': 'cargo', 'verbose_name_plural': 'cargos'},
        ),
    ]
