# Generated by Django 2.2.5 on 2019-10-26 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0018_auto_20191025_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraFieldType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('model', models.CharField(blank=True, choices=[('Instalacion', 'Instalacion'), ('Employee', 'Employee')], max_length=10, null=True, verbose_name='Model')),
                ('fixed_values', models.BooleanField(default=False, verbose_name='Fixed values')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExtraField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200, verbose_name='Value')),
                ('field_type', models.ForeignKey(blank=True, help_text='Only field types with fixed values can be chosen to add global values.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extra_fields', to='facilities.ExtraFieldType', verbose_name='Field type')),
            ],
            options={
                'ordering': ['field_type__name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='extra_fields',
            field=models.ManyToManyField(to='facilities.ExtraField', verbose_name='Extra fields'),
        ),
        migrations.AddField(
            model_name='instalacion',
            name='extra_fields',
            field=models.ManyToManyField(to='facilities.ExtraField', verbose_name='Extra fields'),
        ),
    ]
