# Generated by Django 2.2.5 on 2019-10-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0019_auto_20191026_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrafieldtype',
            name='model',
            field=models.CharField(blank=True, choices=[('Instalacion', 'Instalacion'), ('Employee', 'Employee')], max_length=40, null=True, verbose_name='Model'),
        ),
    ]
