# Generated by Django 2.2.5 on 2019-10-27 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0020_auto_20191026_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='extra_fields',
        ),
        migrations.RemoveField(
            model_name='extrafieldtype',
            name='fixed_values',
        ),
        migrations.RemoveField(
            model_name='instalacion',
            name='extra_fields',
        ),
        migrations.AddField(
            model_name='extrafield',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.Employee', verbose_name='Funcionario'),
        ),
        migrations.AddField(
            model_name='extrafield',
            name='instalacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.Instalacion', verbose_name='Instalación'),
        ),
    ]
