# Generated by Django 2.2.5 on 2019-10-29 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0021_auto_20191027_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extrafieldtype',
            options={'ordering': ['name'], 'verbose_name': 'metadato', 'verbose_name_plural': 'metadatos'},
        ),
        migrations.AlterField(
            model_name='extrafield',
            name='field_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extra_fields', to='facilities.ExtraFieldType', verbose_name='Field type'),
        ),
        migrations.AlterField(
            model_name='extrafieldtype',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='extrafieldtype',
            name='model',
            field=models.CharField(blank=True, choices=[('Instalacion', 'Instalacion'), ('Employee', 'Employee')], max_length=40, null=True, verbose_name='Tabla asociada'),
        ),
        migrations.AlterField(
            model_name='extrafieldtype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
