# Generated by Django 2.2.5 on 2019-10-30 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('political_division', '0015_auto_20191029_1628'),
        ('facilities', '0022_auto_20191029_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrafield',
            name='corregimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='political_division.Corregimiento', verbose_name='Corregimiento'),
        ),
        migrations.AddField(
            model_name='extrafield',
            name='distrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='political_division.Distrito', verbose_name='Distrito'),
        ),
        migrations.AddField(
            model_name='extrafield',
            name='poblado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='political_division.Poblado', verbose_name='Poblado'),
        ),
        migrations.AddField(
            model_name='extrafield',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='political_division.Provincia', verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='extrafield',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='political_division.Region', verbose_name='Región'),
        ),
        migrations.AlterField(
            model_name='extrafieldtype',
            name='model',
            field=models.CharField(blank=True, choices=[('Instalacion', 'Instalación'), ('Employee', 'Funcionario'), ('Provincia', 'Provincia'), ('Region', 'Región'), ('Distrito', 'Distrito'), ('Corregimiento', 'Corregimiento'), ('Poblado', 'Poblado')], max_length=40, null=True, verbose_name='Tabla asociada'),
        ),
    ]
