# Generated by Django 2.2.5 on 2019-10-30 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0023_auto_20191030_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrafield',
            name='field_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_fields', to='facilities.ExtraFieldType', verbose_name='Field type'),
        ),
    ]
