# Generated by Django 2.2.5 on 2020-03-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0024_auto_20191030_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='instalacion',
        ),
        migrations.AddField(
            model_name='employee',
            name='instalaciones',
            field=models.ManyToManyField(blank=True, to='facilities.Instalacion'),
        ),
    ]
