# Generated by Django 2.2.5 on 2020-03-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0025_auto_20200323_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id_minsa',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Identificador Institucional'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='identity_card',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Salario Mensual'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio de labores'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'PERMANENTE'), (2, 'PERS TRANS DE INVERS'), (3, 'PERS TRANSITORIO')], default=1, null=True, verbose_name='Estatus'),
        ),
    ]
