# Generated by Django 2.2.5 on 2020-03-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0026_auto_20200323_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'PERMANENTE'), (2, 'PERS TRANS DE INVERS'), (3, 'PERS TRANSITORIO')], null=True, verbose_name='Estatus'),
        ),
    ]
