# Generated by Django 2.2.5 on 2020-03-23 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0027_auto_20200323_0806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesion', models.CharField(max_length=150, verbose_name='Profesión')),
                ('codigo', models.CharField(max_length=2, unique=True, verbose_name='Código')),
            ],
            options={
                'verbose_name_plural': 'profesiones',
                'verbose_name': 'profesion',
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=150, verbose_name='Especialidad')),
                ('codigo', models.CharField(max_length=2, unique=True, verbose_name='Código')),
                ('profesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.Profesion', verbose_name='Profesión')),
            ],
            options={
                'verbose_name_plural': 'especialidades',
                'verbose_name': 'especialidad',
            },
        ),
    ]
