# Generated by Django 2.2.5 on 2020-03-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0028_especialidad_profesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='especialidades',
            field=models.ManyToManyField(blank=True, to='facilities.Especialidad'),
        ),
    ]
