# Generated by Django 2.2.5 on 2020-03-27 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0029_employee_especialidades'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadesCriticas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de registro')),
                ('ingresos', models.IntegerField(blank=True, null=True, verbose_name='Ingresos')),
                ('intubados', models.IntegerField(blank=True, null=True, verbose_name='Intubados')),
                ('ventiladores', models.IntegerField(blank=True, null=True, verbose_name='Ventiladores')),
                ('muertes', models.IntegerField(blank=True, null=True, verbose_name='Muertes')),
                ('instalacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.Instalacion', verbose_name='Instalación')),
            ],
            options={
                'verbose_name_plural': 'unidades criticas',
                'verbose_name': 'unidad critica',
            },
        ),
    ]
