# Generated by Django 2.2.5 on 2020-03-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0030_unidadescriticas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadescriticas',
            name='reg_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro'),
        ),
    ]
