# Generated by Django 2.2.5 on 2020-03-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0031_auto_20200327_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadescriticas',
            name='reg_date',
            field=models.DateTimeField(verbose_name='Fecha de registro'),
        ),
    ]
