# Generated by Django 2.2.5 on 2020-03-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0032_auto_20200327_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadescriticas',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
    ]
