# Generated by Django 2.2.5 on 2020-03-28 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0033_unidadescriticas_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadescriticas',
            name='hospitalizados',
            field=models.IntegerField(blank=True, help_text='Total de pacientes hospitalizados COVID-19', null=True, verbose_name='Hospitalizados'),
        ),
        migrations.AddField(
            model_name='unidadescriticas',
            name='pacientes_uci',
            field=models.IntegerField(blank=True, help_text='Total de pacientes COVID-19 en UCI', null=True, verbose_name='Pacientes en UCI'),
        ),
        migrations.AlterField(
            model_name='unidadescriticas',
            name='ingresos',
            field=models.IntegerField(blank=True, help_text='Cantidad de nuevos ingresos a UCI', null=True, verbose_name='Ingresos'),
        ),
        migrations.AlterField(
            model_name='unidadescriticas',
            name='intubados',
            field=models.IntegerField(blank=True, help_text='Total de intubados COVID-19', null=True, verbose_name='Intubados'),
        ),
        migrations.AlterField(
            model_name='unidadescriticas',
            name='muertes',
            field=models.IntegerField(blank=True, help_text='Cantidad de nuevas muertes por COVID-19', null=True, verbose_name='Muertes'),
        ),
        migrations.AlterField(
            model_name='unidadescriticas',
            name='ventiladores',
            field=models.IntegerField(blank=True, help_text='Total de ventiladores en uso COVID-19', null=True, verbose_name='Ventiladores'),
        ),
    ]
