# Generated by Django 2.2.5 on 2020-03-29 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0034_auto_20200328_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrafield',
            name='unidades_criticas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.UnidadesCriticas', verbose_name='Unidades Críticas'),
        ),
        migrations.AlterField(
            model_name='extrafieldtype',
            name='model',
            field=models.CharField(blank=True, choices=[('Instalacion', 'Instalación'), ('Employee', 'Funcionario'), ('Provincia', 'Provincia'), ('Region', 'Región'), ('Distrito', 'Distrito'), ('Corregimiento', 'Corregimiento'), ('Poblado', 'Poblado'), ('UnidadesCriticas', 'Unidades Críticas')], max_length=40, null=True, verbose_name='Tabla asociada'),
        ),
    ]
