# Generated by Django 2.2.5 on 2020-03-31 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0035_auto_20200329_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.Employee', verbose_name='Funcionario'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='instalacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.Instalacion', verbose_name='Instalación'),
        ),
    ]
