# Generated by Django 2.2.5 on 2020-03-31 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0037_instalacion_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
    ]
