# Generated by Django 2.2.5 on 2020-04-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0038_employee_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadescriticas',
            name='egresos_uci',
            field=models.IntegerField(blank=True, help_text='Cantidad de egresos de UCI', null=True, verbose_name='Egresos de UCI'),
        ),
    ]
