# Generated by Django 2.2.5 on 2020-04-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0039_unidadescriticas_egresos_uci'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadescriticas',
            name='anestesiologos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Médicos Anestesiólogos'),
        ),
        migrations.AddField(
            model_name='unidadescriticas',
            name='camas_covid',
            field=models.IntegerField(blank=True, help_text='Camas ocupadas por COVID-19', null=True, verbose_name='Camas COVID-19'),
        ),
        migrations.AddField(
            model_name='unidadescriticas',
            name='camas_otro',
            field=models.IntegerField(blank=True, help_text='Camas ocupadas por otras causas', null=True, verbose_name='Camas otras causas'),
        ),
        migrations.AddField(
            model_name='unidadescriticas',
            name='camas_semi',
            field=models.IntegerField(blank=True, help_text='Total de camas en cuidados semi intensivos disponibles', null=True, verbose_name='Camas Semi Intensivos'),
        ),
        migrations.AddField(
            model_name='unidadescriticas',
            name='camas_uci',
            field=models.IntegerField(blank=True, help_text='Total de camas en cuidados intensivos disponibles', null=True, verbose_name='Camas UCI'),
        ),
        migrations.AddField(
            model_name='unidadescriticas',
            name='enfermeros',
            field=models.IntegerField(blank=True, null=True, verbose_name='Enfermeros'),
        ),
        migrations.AddField(
            model_name='unidadescriticas',
            name='intensivistas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Médicos Intensivistas'),
        ),
        migrations.AddField(
            model_name='unidadescriticas',
            name='internistas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Médicos Internistas'),
        ),
        migrations.AddField(
            model_name='unidadescriticas',
            name='neumologos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Médicos Anestesiólogos'),
        ),
        migrations.AddField(
            model_name='unidadescriticas',
            name='tecnicos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Técnicos/Auxiliares Enfermería'),
        ),
        migrations.AddField(
            model_name='unidadescriticas',
            name='vent_dispo',
            field=models.IntegerField(blank=True, help_text='Total de ventiladores disponibles', null=True, verbose_name='Ventiladores disponibles'),
        ),
        migrations.AddField(
            model_name='unidadescriticas',
            name='vent_uso',
            field=models.IntegerField(blank=True, help_text='Número de ventiladores en uso', null=True, verbose_name='Ventiladores en uso'),
        ),
    ]
