# Generated by Django 2.2.5 on 2020-04-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0040_auto_20200403_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadescriticas',
            name='neumologos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Médicos Neumólogos'),
        ),
    ]
