# Generated by Django 2.2.5 on 2020-04-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0041_auto_20200404_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadescriticas',
            name='observaciones_rh',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
    ]
