# Generated by Django 2.2.5 on 2020-04-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0042_unidadescriticas_observaciones_rh'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadescriticas',
            name='defunciones_covid',
            field=models.IntegerField(blank=True, help_text='Total defunciones por COVID-19 (sospechoso y confirmado)', null=True, verbose_name='Defunciones por COVID-19'),
        ),
        migrations.AddField(
            model_name='unidadescriticas',
            name='infectologos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Médicos Infectólogo'),
        ),
        migrations.AddField(
            model_name='unidadescriticas',
            name='observaciones_camas',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='unidadescriticas',
            name='pacientes_covid_ext',
            field=models.IntegerField(blank=True, help_text='Pacientes con COVID-19 que fueron extubados', null=True, verbose_name='Pacientes con COVID-19 que fueron extubados'),
        ),
        migrations.AddField(
            model_name='unidadescriticas',
            name='pacientes_covid_int',
            field=models.IntegerField(blank=True, help_text='Total pacientes COVID-19 sospechosos y confirmados con intubacion', null=True, verbose_name='Pacientes con COVID-19 con intubacion'),
        ),
        migrations.AddField(
            model_name='unidadescriticas',
            name='pacientes_traslado',
            field=models.IntegerField(blank=True, help_text='Pacientes trasladados de UCI a sala', null=True, verbose_name='Pacientes trasladados de UCI a sala'),
        ),
        migrations.AddField(
            model_name='unidadescriticas',
            name='pacientes_vma',
            field=models.IntegerField(blank=True, help_text='Total pacientes COVID-19 sospechosos y confirmados con ventilación mecánica asistida', null=True, verbose_name='Pacientes con COVID-19 con VMA'),
        ),
        migrations.AddField(
            model_name='unidadescriticas',
            name='vent_otro',
            field=models.IntegerField(blank=True, help_text='Total de ventiladores para pacientes con otras patologías', null=True, verbose_name='Ventiladores ocupados con otras patologías'),
        ),
        migrations.AlterField(
            model_name='unidadescriticas',
            name='camas_covid',
            field=models.IntegerField(blank=True, help_text='Camas ocupadas con pacientes COVID-19 sospechosos y confirmados internados en intensivo y semi intensivo', null=True, verbose_name='Camas ocupadas por COVID-19'),
        ),
        migrations.AlterField(
            model_name='unidadescriticas',
            name='camas_otro',
            field=models.IntegerField(blank=True, help_text='Camas ocupadas con pacientes con otras patologías', null=True, verbose_name='Camas otras causas'),
        ),
        migrations.AlterField(
            model_name='unidadescriticas',
            name='camas_semi',
            field=models.IntegerField(blank=True, help_text='Total de camas en cuidados semi intensivos disponibles (estén o no ocupadas)', null=True, verbose_name='Camas Semi Intensivos'),
        ),
        migrations.AlterField(
            model_name='unidadescriticas',
            name='camas_uci',
            field=models.IntegerField(blank=True, help_text='Total de camas UCI disponibles en el hospital (estén o no ocupadas)', null=True, verbose_name='Camas UCI'),
        ),
        migrations.AlterField(
            model_name='unidadescriticas',
            name='vent_dispo',
            field=models.IntegerField(blank=True, help_text='Total de ventiladores que tiene el hospital (estén o no ocupados) Sumar ventiladores de transporte y estacionarios', null=True, verbose_name='Ventiladores disponibles'),
        ),
    ]
