# Generated by Django 2.2.5 on 2020-04-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0043_auto_20200407_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadescriticas',
            name='anestesiologos_dispo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Disponibles'),
        ),
        migrations.AddField(
            model_name='unidadescriticas',
            name='enfermeros_dispo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Disponibles'),
        ),
        migrations.AddField(
            model_name='unidadescriticas',
            name='infectologos_dispo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Disponibles'),
        ),
        migrations.AddField(
            model_name='unidadescriticas',
            name='intensivistas_dispo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Disponibles'),
        ),
        migrations.AddField(
            model_name='unidadescriticas',
            name='internistas_dispo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Disponibles'),
        ),
        migrations.AddField(
            model_name='unidadescriticas',
            name='neumologos_dispo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Disponibles'),
        ),
        migrations.AddField(
            model_name='unidadescriticas',
            name='tecnicos_dispo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Disponibles'),
        ),
        migrations.AlterField(
            model_name='unidadescriticas',
            name='anestesiologos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Médicos Anestesiólogos Totales'),
        ),
        migrations.AlterField(
            model_name='unidadescriticas',
            name='enfermeros',
            field=models.IntegerField(blank=True, null=True, verbose_name='Enfermeros Totales'),
        ),
        migrations.AlterField(
            model_name='unidadescriticas',
            name='intensivistas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Médicos Intensivistas Totales'),
        ),
        migrations.AlterField(
            model_name='unidadescriticas',
            name='internistas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Médicos Internistas Totales'),
        ),
        migrations.AlterField(
            model_name='unidadescriticas',
            name='neumologos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Médicos Neumólogos Totales'),
        ),
        migrations.AlterField(
            model_name='unidadescriticas',
            name='tecnicos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Técnicos/Auxiliares Enfermería Totales'),
        ),
    ]
