# Generated by Django 2.2.5 on 2020-04-08 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0045_ucentity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidadescriticas',
            name='hospitalizados',
        ),
    ]
