# Generated by Django 2.2.5 on 2020-04-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0047_auto_20200414_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadescriticas',
            name='pacientes_vma_sala',
            field=models.IntegerField(blank=True, help_text='Pacientes sospechosos y confirmados con COVID-19 con VMA en sala (no incluir intensivo ni semi intensivo).', null=True, verbose_name='Pacientes con COVID-19 con VMA en sala'),
        ),
    ]
