# Generated by Django 2.2.5 on 2020-04-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0048_unidadescriticas_pacientes_vma_sala'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidadescriticas',
            name='vent_uso',
        ),
        migrations.AddField(
            model_name='unidadescriticas',
            name='extubados',
            field=models.IntegerField(blank=True, help_text='Total de extubados COVID-19', null=True, verbose_name='Extubados'),
        ),
    ]
