# Generated by Django 2.2.5 on 2020-04-15 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0049_auto_20200414_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadescriticas',
            name='aprovado',
            field=models.BooleanField(default=False, verbose_name='Aprobado'),
        ),
    ]
