# Generated by Django 2.2.5 on 2020-04-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0050_unidadescriticas_aprovado'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadescriticas',
            name='pacientes_uci_otro',
            field=models.IntegerField(blank=True, help_text='Pacientes con otras patologías en UCI y SEMI', null=True, verbose_name='Pacientes en UCI Otras'),
        ),
        migrations.AddField(
            model_name='unidadescriticas',
            name='ventilados_otro',
            field=models.IntegerField(blank=True, help_text='Pacientes con otras patologías con ventilación mecánica asistida', null=True, verbose_name='Pacientes VMA Otras'),
        ),
        migrations.AlterField(
            model_name='unidadescriticas',
            name='egresos_uci',
            field=models.IntegerField(blank=True, help_text='Pacientes sospechosos y confirmados COVID-19 que fueron trasladados de UCI a sala el día de hoy', null=True, verbose_name='Trasladados de UCI'),
        ),
        migrations.AlterField(
            model_name='unidadescriticas',
            name='extubados',
            field=models.IntegerField(blank=True, help_text='Pacientes COVID-19 extubados el día de hoy', null=True, verbose_name='Extubados'),
        ),
        migrations.AlterField(
            model_name='unidadescriticas',
            name='ingresos',
            field=models.IntegerField(blank=True, help_text='Pacientes sospechosos y confirmados COVID-19 que ingresaron a UCI el día de hoy', null=True, verbose_name='Ingresos a UCI'),
        ),
        migrations.AlterField(
            model_name='unidadescriticas',
            name='intubados',
            field=models.IntegerField(blank=True, help_text='Pacientes COVID-19 sospechosos y confirmados intubados', null=True, verbose_name='Intubados'),
        ),
        migrations.AlterField(
            model_name='unidadescriticas',
            name='muertes',
            field=models.IntegerField(blank=True, help_text='Defunciones por COVID-19 totales (sumar sospechosos y confirmados)', null=True, verbose_name='Defunciones por COVID-19:'),
        ),
        migrations.AlterField(
            model_name='unidadescriticas',
            name='pacientes_uci',
            field=models.IntegerField(blank=True, help_text='Pacientes COVID-19 sospechosos y confirmados en UCI y SEMI', null=True, verbose_name='Pacientes en UCI COVID-19'),
        ),
        migrations.AlterField(
            model_name='unidadescriticas',
            name='ventiladores',
            field=models.IntegerField(blank=True, help_text='Pacientes COVID-19 sospechosos y confirmados con ventilación mecánica asistida', null=True, verbose_name='Pacientes VMA COVID-19'),
        ),
    ]
