# Generated by Django 2.2.5 on 2020-04-23 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0051_auto_20200421_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unidadescriticas',
            old_name='aprovado',
            new_name='aprobado',
        ),
    ]
