# Generated by Django 2.2.5 on 2020-05-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0052_auto_20200423_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadescriticas',
            name='reg_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de registro'),
        ),
    ]
