# Generated by Django 2.2.5 on 2020-05-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0053_auto_20200504_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadescriticas',
            name='reg_date',
            field=models.DateTimeField(verbose_name='Fecha de registro'),
        ),
    ]
