# Generated by Django 2.2.5 on 2020-06-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0055_auto_20200603_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadescriticas',
            name='pacientes_vma_semi',
            field=models.IntegerField(blank=True, help_text='Total pacientes COVID-19 sospechosos y confirmados con ventilación mecánica asistida en Semi-intensivo', null=True, verbose_name='Pacientes con COVID-19 con VMA en Semi-intensivo'),
        ),
        migrations.AddField(
            model_name='unidadescriticas',
            name='pacientes_vma_semi_fijo',
            field=models.IntegerField(blank=True, help_text='Pacientes con COVID-19 con VMA en UCI en Semi-intensivo tipo fijo', null=True, verbose_name='Ventilador tipo fijo'),
        ),
        migrations.AddField(
            model_name='unidadescriticas',
            name='pacientes_vma_semi_trans',
            field=models.IntegerField(blank=True, help_text='Pacientes con COVID-19 con VMA en UCI en Semi-intensivo tipo transorte', null=True, verbose_name='Ventilador tipo trasporte'),
        ),
        migrations.AlterField(
            model_name='unidadescriticas',
            name='pacientes_vma',
            field=models.IntegerField(blank=True, help_text='Total pacientes COVID-19 sospechosos y confirmados con ventilación mecánica asistida en UCI', null=True, verbose_name='Pacientes con COVID-19 con VMA en UCI'),
        ),
        migrations.AlterField(
            model_name='unidadescriticas',
            name='pacientes_vma_fijo',
            field=models.IntegerField(blank=True, help_text='Pacientes con COVID-19 con VMA en UCI tipo fijo', null=True, verbose_name='Ventilador tipo fijo'),
        ),
        migrations.AlterField(
            model_name='unidadescriticas',
            name='pacientes_vma_trans',
            field=models.IntegerField(blank=True, help_text='Pacientes con COVID-19 con VMA en UCI tipo transorte', null=True, verbose_name='Ventilador tipo trasporte'),
        ),
    ]
