# Generated by Django 2.2.5 on 2020-06-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0056_auto_20200603_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadescriticas',
            name='pacientes_vma_fijo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ventilador tipo fijo'),
        ),
        migrations.AlterField(
            model_name='unidadescriticas',
            name='pacientes_vma_sala_fijo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ventilador tipo fijo'),
        ),
        migrations.AlterField(
            model_name='unidadescriticas',
            name='pacientes_vma_sala_trans',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ventilador tipo trasporte'),
        ),
        migrations.AlterField(
            model_name='unidadescriticas',
            name='pacientes_vma_semi_fijo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ventilador tipo fijo'),
        ),
        migrations.AlterField(
            model_name='unidadescriticas',
            name='pacientes_vma_semi_trans',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ventilador tipo trasporte'),
        ),
        migrations.AlterField(
            model_name='unidadescriticas',
            name='pacientes_vma_trans',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ventilador tipo trasporte'),
        ),
        migrations.AlterField(
            model_name='unidadescriticas',
            name='vent_dispo_fijo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ventilador tipo fijo'),
        ),
        migrations.AlterField(
            model_name='unidadescriticas',
            name='vent_dispo_trans',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ventilador tipo trasporte'),
        ),
        migrations.AlterField(
            model_name='unidadescriticas',
            name='vent_otro_fijo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ventilador tipo fijo'),
        ),
        migrations.AlterField(
            model_name='unidadescriticas',
            name='vent_otro_trans',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ventilador tipo trasporte'),
        ),
    ]
