from facilities.models import Instalacion, UCEntity
from rest_framework import serializers

class InstalacionSerializer(serializers.Serializer):
    id = serializers.IntegerField()
    instalacion = serializers.CharField()
    cod_inst = serializers.CharField()
    tipo_instalacion = serializers.StringRelatedField()
    nivel = serializers.StringRelatedField()
    latitude = serializers.DecimalField(max_digits=9, decimal_places=6)
    longitude = serializers.DecimalField(max_digits=9, decimal_places=6)
    corregimiento = serializers.StringRelatedField()
    dependencia = serializers.StringRelatedField()
    region_dependencia = serializers.StringRelatedField()
    servicios = serializers.StringRelatedField(many=True)

    class Meta:
        model = Instalacion


class UCEntitySerializer(serializers.Serializer):
    instalacion_id = serializers.IntegerField()
    instalacion = serializers.CharField()
    latitude = serializers.DecimalField(max_digits=9, decimal_places=6)
    longitude = serializers.DecimalField(max_digits=9, decimal_places=6)
    region = serializers.CharField()
    provincia = serializers.CharField()
    distrito = serializers.CharField()
    corregimiento = serializers.CharField()
    dependencia = serializers.CharField()
    tipo_instalacion = serializers.CharField()
    nivel = serializers.CharField()
    director_medico = serializers.CharField()
    subdirector = serializers.CharField()
    camas_totales = serializers.CharField()
    camas_covid19 = serializers.CharField()
    camas_totales_uci = serializers.CharField()
    covid19_uci = serializers.CharField()
    ventiladores_fijos = serializers.CharField()
    ventiladores_transporte = serializers.CharField()
    cunas_covid19 = serializers.CharField()
    carpas_ops = serializers.CharField()
    contenedores = serializers.CharField()
    ventiladores = serializers.CharField()
    camas_ac = serializers.CharField()
    ventiladores_mecanicos = serializers.CharField()
    camas_uci_desc = serializers.CharField()
    camas_semi_desc = serializers.CharField()
    vent_uso = serializers.IntegerField()
    ingresos = serializers.IntegerField()
    egresos_uci = serializers.IntegerField()
    intubados = serializers.IntegerField()
    con_ventilador = serializers.IntegerField()
    muertes = serializers.IntegerField()
    pacientes_uci = serializers.IntegerField()
    camas_uci = serializers.IntegerField()
    camas_semi = serializers.IntegerField()
    camas_covid = serializers.IntegerField()
    camas_otro = serializers.IntegerField()
    vent_dispo = serializers.IntegerField()
    pacientes_vma = serializers.IntegerField()
    vent_otro = serializers.IntegerField()
    pacientes_covid_int = serializers.IntegerField()
    pacientes_covid_ext = serializers.IntegerField()
    pacientes_traslado = serializers.IntegerField()
    defunciones_covid = serializers.IntegerField()
    intensivistas = serializers.IntegerField()
    intensivistas_dispo = serializers.IntegerField()
    internistas = serializers.IntegerField()
    internistas_dispo = serializers.IntegerField()
    infectologos = serializers.IntegerField()
    infectologos_dispo = serializers.IntegerField()
    anestesiologos = serializers.IntegerField()
    anestesiologos_dispo = serializers.IntegerField()
    neumologos = serializers.IntegerField()
    neumologos_dispo = serializers.IntegerField()
    enfermeros = serializers.IntegerField()
    enfermeros_dispo = serializers.IntegerField()
    tecnicos = serializers.IntegerField()
    tecnicos_dispo = serializers.IntegerField()

    class Meta:
        model = UCEntity