# Generated by Django 2.2.5 on 2019-10-29 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('political_division', '0015_auto_20191029_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indigenous', models.IntegerField(blank=True, null=True, verbose_name='Indígena')),
                ('non_indigenous', models.IntegerField(blank=True, null=True, verbose_name='No indígena')),
                ('residences', models.IntegerField(blank=True, null=True, verbose_name='Total de viviendas')),
                ('contra_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='political_division.Poblado', to_field='contra_key', verbose_name='Población')),
            ],
        ),
    ]
