# Generated by Django 2.2.5 on 2019-10-30 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='population',
            options={'verbose_name': 'Población', 'verbose_name_plural': 'Población'},
        ),
    ]
